# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43"
          Invoke-WebRequest -UseBasicParsing -Uri "https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.33-winx64.zip" `
            -WebSession $session `
            -Headers @{
               "Accept"="text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
               "Accept-Encoding"="gzip, deflate, br"
               "Accept-Language"="en-US,en;q=0.9,ru;q=0.8"
               "Referer"="https://dev.mysql.com/"
               "Sec-Fetch-Dest"="document"
               "Sec-Fetch-Mode"="navigate"
               "Sec-Fetch-Site"="same-site"
               "Sec-Fetch-User"="?1"
               "Upgrade-Insecure-Requests"="1"
               "sec-ch-ua"="`"Not.A/Brand`";v=`"8`", `"Chromium`";v=`"114`", `"Microsoft Edge`";v=`"114`""
               "sec-ch-ua-mobile"="?0"
               "sec-ch-ua-platform"="`"Windows`""
          } -OutFile 'mysql-8.0.33-winx64.zip'
          Get-Item 'mysql-8.0.33-winx64.zip'
        shell: powershell
